[server]
headless = true
address = "localhost"
port = 8501
enableCORS = false
enableXsrfProtection = true

[theme]
primaryColor = "#4CAF50"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[browser]
gatherUsageStats = false

[runner]
fastRerenderThreshold = 1000

[client]
toolbarMode = "minimal"