[server]
headless = true
address = "localhost"
port = 8501
enableCORS = false
enableXsrfProtection = true

[theme]
primaryColor = "#4CAF50"
backgroundColor = "#262730"
secondaryBackgroundColor = "#1E1E1E"
textColor = "#FAFAFA"
font = "sans serif"

[browser]
gatherUsageStats = false

[runner]
fastRerenderThreshold = 1000

[client]
toolbarMode = "minimal" 